# Generated by Django 4.2.3 on 2024-05-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_alter_certificate_certifying_institution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="certifyinginstitution",
            name="url",
            field=models.URLField(),
        ),
    ]
