# Generated by Django 4.2.3 on 2024-05-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_alter_certificate_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="profiles",
            field=models.ManyToManyField(
                related_name="certificates", to="projects.profile"
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="timestamp",
            field=models.DateField(auto_now_add=True),
        ),
    ]
